alias: Batterien Lade-Synchronisation
description: Lädt nur die schwächere Batterie bei >2% Unterschied, ohne Zwischenschaltung
triggers:
  - minutes: /5
    trigger: time_pattern
  - event: start
    trigger: homeassistant
actions:
  - variables:
      batt1_soc: "{{ states('sensor.bms01_pack_soc') | float(0) }}"
      batt2_soc: "{{ states('sensor.bms02_pack_soc') | float(0) }}"
      soc_diff: "{{ batt1_soc - batt2_soc }}"
      abs_diff: "{{ (soc_diff) | abs }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ soc_diff > 2 }}"
        sequence:
          - target:
              entity_id: switch.bms01_pack_chargefet
            action: switch.turn_off
            data: {}
          - target:
              entity_id: switch.bms02_pack_chargefet
            action: switch.turn_on
            data: {}
      - conditions:
          - condition: template
            value_template: "{{ soc_diff < -2 }}"
        sequence:
          - target:
              entity_id: switch.bms02_pack_chargefet
            action: switch.turn_off
            data: {}
          - target:
              entity_id: switch.bms01_pack_chargefet
            action: switch.turn_on
            data: {}
    default:
      - target:
          entity_id:
            - switch.bms01_pack_chargefet
            - switch.bms02_pack_chargefet
        action: switch.turn_on
        data: {}
mode: restart
